### ISSUE TITLE
tisan-web-ide  grpc client 感觉应该缺少了 grpc server 服务

### ISSUE THREAD

**Issue by nskyzier** [PandoCloud/pando-cloud#34]
你好！
tisan-web-ide， 试验的时候  grpc client 出现错误：
 /home/ubuntu/tisan-web-ide/service/grpc.js:4
 var client = new product_grpc.ProductCMDS(config.grpc[0],grpc.Credentials.createInsecure());

TypeError: Cannot read property 'createInsecure' of undefined
 at Object. (/home/ubuntu/tisan-web-ide/service/grpc.js:4:74)

感觉应该缺少 grpc server 服务，请问这个grpc server 侧是不是缺少了？
 grpc: [ 'localhost:20311' ],

---------------------------------------------------------------------------------------------------------

express-session deprecated req.secret; provide secret option app.js:31:9
D0716 14:27:09.722562038    6570 ev_posix.c:101]             Using polling engin                                   e: poll
/home/ubuntu/tisan-web-ide/service/grpc.js:4
var client = new product_grpc.ProductCMDS(config.grpc[0],grpc.Credentials.create                                   Insecure());
                                                                         ^

TypeError: Cannot read property 'createInsecure' of undefined
    at Object.<anonymous> (/home/ubuntu/tisan-web-ide/service/grpc.js:4:74)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/tisan-web-ide/routes/workspace.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/tisan-web-ide/app.js:59:23)
    at Module._compile (module.js:409:26)

**Comment by Zhang-Jia** [comment]
我也出现类似问题，现在还有人回答吗？感觉开发者都放弃维护了。

**Comment by ruizeng** [comment]
你好 @Zhang-Jia @nskyzier ，tisan-web-ide项目是基于此项目开发的第三方组件，和pando cloud本身并没有直接关系，我也无法回答里面的问题。目前可能tisan-web-ide的开发者没有维护了，不过关于pando cloud的任何疑问我都会解答，谢谢。

**Comment by coolcm** [comment]
![qq 20160909214116](https://cloud.githubusercontent.com/assets/16472516/18389017/6ebf1dde-76d6-11e6-9a71-24011abe0243.png)
